# Generated by Django 4.0.10 on 2023-03-04 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='authorr',
        ),
    ]
